name: Django tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  django-tests:
    name: django-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: install deps and run tests
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install -r requirements.txt
          pip install .
          python manage.py test
        shell: bash
